name: First Workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-Latest

    steps:
      - name: Print a welcome message
        run: echo "Welcome to our first github actions worflow!"

      - name: Checkout repository
        uses: actions/checkout@v6-beta

      - name: List repository files
        run: ls -la

        
